DROP DATABASE IF EXISTS test1;
CREATE DATABASE test1;
USE test1;

##部门表
CREATE TABLE DEPT
(
    DEPTNO int PRIMARY KEY,#部门编号
    DNAME  VARCHAR(14),    # 部门名称
    LOC    VARCHAR(13)     # 部门地址
);

INSERT INTO DEPT
VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT
VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT
VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT
VALUES (40, 'OPERATIONS', 'BOSTON');

##员工表
# DROP IF EXISTS TABLE EMP;
CREATE TABLE EMP
(
    EMPNO    int PRIMARY KEY, #员工编号
    ENAME    VARCHAR(10),     #员工姓名
    JOB      VARCHAR(9),      #员工工作
    MGR      int,             #员工直属领导编号
    HIREDATE DATE,            #入职时间
    SAL      double,          #工资
    COMM     double,          #奖金
    DEPTNO   int              #对应dept表的外键
);
## 添加 部门 和 员工 之间的主外键关系
ALTER TABLE EMP
    ADD CONSTRAINT FOREIGN KEY EMP (DEPTNO) REFERENCES DEPT (DEPTNO);

INSERT INTO EMP
VALUES (7369, 'SMITH', 'CLERK', 7902, '1980-12-17', 800, NULL, 20);
INSERT INTO EMP
VALUES (7499, 'ALLEN', 'SALESMAN', 7698, '1981-02-20', 1600, 300, 30);
INSERT INTO EMP
VALUES (7521, 'WARD', 'SALESMAN', 7698, '1981-02-22', 1250, 500, 30);
INSERT INTO EMP
VALUES (7566, 'JONES', 'MANAGER', 7839, '1981-04-02', 2975, NULL, 20);
INSERT INTO EMP
VALUES (7654, 'MARTIN', 'SALESMAN', 7698, '1981-09-28', 1250, 1400, 30);
INSERT INTO EMP
VALUES (7698, 'BLAKE', 'MANAGER', 7839, '1981-05-01', 2850, NULL, 30);
INSERT INTO EMP
VALUES (7782, 'CLARK', 'MANAGER', 7839, '1981-06-09', 2450, NULL, 10);
INSERT INTO EMP
VALUES (7788, 'SCOTT', 'ANALYST', 7566, '1987-07-03', 3000, NULL, 20);
INSERT INTO EMP
VALUES (7839, 'KING', 'PRESIDENT', NULL, '1981-11-17', 5000, NULL, 10);
INSERT INTO EMP
VALUES (7844, 'TURNER', 'SALESMAN', 7698, '1981-09-08', 1500, 0, 30);
INSERT INTO EMP
VALUES (7876, 'ADAMS', 'CLERK', 7788, '1987-07-13', 1100, NULL, 20);
INSERT INTO EMP
VALUES (7900, 'JAMES', 'CLERK', 7698, '1981-12-03', 950, NULL, 30);
INSERT INTO EMP
VALUES (7902, 'FORD', 'ANALYST', 7566, '1981-12-03', 3000, NULL, 20);
INSERT INTO EMP
VALUES (7934, 'MILLER', 'CLERK', 7782, '1981-01-23', 1300, NULL, 10);

#工资等级表
# DROP IF EXISTS TABLE SALGRADE;
CREATE TABLE SALGRADE
(
    GRADE int,    #等级
    LOSAL double, #最低工资
    HISAL double
); #最高工资
INSERT INTO SALGRADE

VALUES (1, 700, 1200);
INSERT INTO SALGRADE
VALUES (2, 1201, 1400);
INSERT INTO SALGRADE
VALUES (3, 1401, 2000);
INSERT INTO SALGRADE
VALUES (4, 2001, 3000);
INSERT INTO SALGRADE
VALUES (5, 3001, 9999);

#多表查询
#1、返回员工的部门名称和部门编号信息。

SELECT ENAME, DNAME, DEPTNO
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

#2、工资水平多于smith的员工信息。
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'SMITH');

#3、返回员工和所属经理的姓名。
SELECT E1.ENAME AS EMPLOYEE_NAME,
       E2.ENAME AS MANAGER_NAME
FROM EMP E1,
     EMP E2
WHERE E1.MGR = E2.EMPNO;

#4、返回雇员的雇佣日期早于其经理雇佣日期的员工及其经理姓名。
SELECT E1.ENAME AS EMPLOYEE_NAME,
       E2.ENAME AS MANAGER_NAME
FROM EMP E1,
     EMP E2
WHERE E1.MGR = E2.EMPNO
  AND E1.HIREDATE < E2.HIREDATE;

#5、返回员工姓名及其所在的部门名称。
SELECT E.ENAME,
       D.DNAME
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO;

#6、返回从事clerk工作的员工姓名和所在部门名称。
SELECT E.ENAME,
       D.DNAME
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.JOB = 'CLERK';

#7、返回部门号及其本部门的最低工资。
SELECT E.DEPTNO,
       MIN(E.SAL) AS MIN_SALARY
FROM EMP E
GROUP BY E.DEPTNO;

#8、返回销售部(sales)所有员工的姓名。
SELECT E.ENAME
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND D.DNAME = 'SALES';

#9、返回工资水平多于平均工资的员工。
SELECT *
FROM EMP
WHERE SAL > (SELECT AVG(SAL)
             FROM EMP);

#10、返回与SCOTT从事相同工作的员工。
SELECT E.ENAME
FROM EMP E,
     EMP S
WHERE E.JOB = S.JOB
  AND S.ENAME = 'SCOTT';

#11、返回与30部门员工工资水平相同的员工姓名与工资。
SELECT E.ENAME,
       E.SAL
FROM EMP E,
     EMP S
WHERE E.SAL = S.SAL
  AND S.DEPTNO = 30;

#12、返回工资高于30部门所有员工工资水平的员工信息。
SELECT *
FROM EMP E
WHERE E.SAL > (SELECT MAX(S.SAL)
               FROM EMP S
               WHERE S.DEPTNO = 30);

#13、返回部门号、部门名、部门所在位置及其每个部门的员工总数。
SELECT D.DEPTNO,
       D.DNAME,
       D.LOC,
       COUNT(E.EMPNO) AS EMP_COUNT
FROM DEPT D
         LEFT JOIN EMP E ON D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO,
         D.DNAME,
         D.LOC;

#14、返回员工的姓名、所在部门名及其工资。
SELECT E.ENAME,
       D.DNAME,
       E.SAL
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO;

#15、返回员工的详细信息。(包括部门名)
SELECT E.EMPNO,
       E.ENAME,
       E.JOB,
       E.MGR,
       E.HIREDATE,
       E.SAL,
       E.COMM,
       D.DNAME,
       D.LOC
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO;

#16、返回员工工作及其从事此工作的最低工资。
SELECT E.JOB,
       MIN(E.SAL) AS MIN_SALARY
FROM EMP E
GROUP BY E.JOB;

#17、计算出员工的年薪，并且以年薪排序。
SELECT E.EMPNO,
       E.ENAME,
       E.SAL * 12 AS ANNUAL_SALARY
FROM EMP E
ORDER BY ANNUAL_SALARY DESC;

#18、返回工资处于第四级别的员工的姓名。
SELECT E.ENAME
FROM EMP E,
     SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
  AND S.GRADE = 4;

#19、返回工资为二等级的职员名字、部门所在地、和二等级的最低工资和最高工资。
SELECT E.ENAME,
       D.LOC,
       S.LOSAL,
       S.HISAL
FROM EMP E,
     DEPT D,
     SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL BETWEEN S.LOSAL AND S.HISAL
  AND S.GRADE = 2;

#20、工资等级多于smith的员工信息。
SELECT *
FROM EMP E,
     SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
  AND S.GRADE > (SELECT S1.GRADE
                 FROM EMP E1,
                      SALGRADE S1
                 WHERE E1.SAL BETWEEN S1.LOSAL AND S1.HISAL
                   AND E1.ENAME = 'SMITH');
